// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwFY2ZwewaM00eUxpV6lgkV5ope3ecwLc',
    appId: '1:1022930003482:web:a9c7af1fa0069e6c1553a3',
    messagingSenderId: '1022930003482',
    projectId: 'fir-authentication-9eb48',
    authDomain: 'fir-authentication-9eb48.firebaseapp.com',
    storageBucket: 'fir-authentication-9eb48.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfLJF3dsO5ix2VpJnFo6XNVkdMHQeDOQQ',
    appId: '1:1022930003482:android:800121e4dcf410201553a3',
    messagingSenderId: '1022930003482',
    projectId: 'fir-authentication-9eb48',
    storageBucket: 'fir-authentication-9eb48.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwFY2ZwewaM00eUxpV6lgkV5ope3ecwLc',
    appId: '1:1022930003482:web:3936300fc9bece491553a3',
    messagingSenderId: '1022930003482',
    projectId: 'fir-authentication-9eb48',
    authDomain: 'fir-authentication-9eb48.firebaseapp.com',
    storageBucket: 'fir-authentication-9eb48.appspot.com',
  );
}
